---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver_config:
      socket: npipe:////./pipe/docker_engine
  - name: centos-7.2
    driver_config:
      socket: npipe:////./pipe/docker_engine

suites:
  - name: default
    run_list:
      - recipe[example::default]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - name: linux-baseline
          supermarket: dev-sec/linux-baseline
    attributes:
